# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d33ee499e6e28b6d3288a7d32518bc5b7c0cb8a5a19edb9dfe3c49f0e3fc04250f540388740392a5f33d59134f3e84b901229384482dc83008d9651fd4cda6e4

test:
  secret_key_base: 7462bc722bfadd0d242a41fa3b132f68b0fedabd21262215351d546faba1351b5375c56b463ed90d30e544b81cd8a6ef23fd373a7ae6293b79f124af4017f9d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
